### ISSUE TITLE
Journal paper for dropletFoam

### ISSUE THREAD

**Issue by unicfdlab** [tgvoskuilen/dropletFoam#3]
Hi, do you have journal or conference article covering equations and assumptions in your dropletFoam solver?

**Comment by tgvoskuilen** [comment]
The main journal paper on this work got rather orphaned after I left the university, but I'm working on some related follow-on work that will be published in the next year or so.

**Comment by unicfdlab** [comment]
Nevertheless, can you share the title of this "orphaned" publication?

**Comment by tgvoskuilen** [comment]
I'm not sure what good that would do. It was never submitted anywhere or publicly released...
